inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

# **************************************************************
# TRY NOT TO ADD OVERRIDES IN THIS FILE
#
# This repo is configured to follow the RuboCop GOV.UK styleguide.
# Any rules you override here will cause this repo to diverge from
# the way we write code in all other GOV.UK repos.
#
# See https://github.com/alphagov/rubocop-govuk/blob/main/CONTRIBUTING.md
# **************************************************************

# It is a convention of this app that the files
# that define a smart answer have a name that matches
# its (hyphenated) URL.
Naming/FileName:
  Exclude:
    - lib/smart_answer_flows/*.rb
    - test/fixtures/smart_answer_flows/*.rb
    - spec/fixtures/flows/*.rb

# Long conditionals are inherent in smart answers, due
# to the complexity of the problem they represent. It is
# a convention of this app to comment the ending of these
# conditionals, to clarify which branches we are on.
Style/CommentedKeyword:
  Enabled: false

# This app does not have a DB
Rails/SaveBang:
  Enabled: false
