---
# Results for each country should be added in the following format:
# results:
#   - title: Country name
#     details:
#       slug: country-slug
#     england_coronavirus_travel:
#       - covid_status: not_red
#         covid_status_applies_at: "2021-12-20T:02:00.000+00:00"
#       - covid_status: red
#         covid_status_applies_at: "2022-02-23T:02:30.000+00:00"
#   - title: Another country name
#     details:
#       slug: another-country-slug
#     england_coronavirus_travel:
#       - covid_status: red
#         covid_status_applies_at: "2021-12-20T:02:00.000+00:00"
