---
results:
  - title: Italy
    details:
      slug: italy
    england_coronavirus_travel:
      rag_status: red
      next_rag_status: green
      next_rag_applies_at:
      status_out_of_date: false
