# Only the current date is used, so this file should only have
# at most 2 items (current and future when uprating is coming),
# and usually 1. The last item in the file should have an end
# date of 2999-01-01
---
- start_date: 2016-04-06
  end_date: 2999-01-01
  affidavit_or_affirmation_for_marriage: 50
  issuing_civil_partnership_certificate: 50
  issuing_civil_partnership_or_marriage_certificate: 50
  issuing_cni_or_nulla_osta: 50
  issuing_custom_and_law_certificate: 50
  issuing_marriage_certificate: 50
  receiving_notice_of_marriage: 50
  receiving_notice_of_civil_partnership: 50
  receiving_notice_of_marriage_or_civil_partnership: 50
  receiving_notice_of_registration: 50
  registering_civil_partnership: 150
  registering_civil_partnership_or_marriage: 150
  registering_marriage: 150
