# Minimum wage calculators use this year and last year's data, so
# make sure we have that at least. If adding a new set of data at
# the end, you may have to update dates/values in the test file.
---
- :start_date: 2021-04-01
  :end_date: 2022-03-31
  :minimum_rates:
  - :min_age: 0
    :max_age: 18
    :rate: 4.62
  - :min_age: 18
    :max_age: 21
    :rate: 6.56
  - :min_age: 21
    :max_age: 23
    :rate: 8.36
  - :min_age: 23
    :max_age: 1000
    :rate: 8.91
  :apprentice_rate: 4.30
  :accommodation_rate: 8.36
- :start_date: 2022-04-01
  :end_date: 3000-01-01
  :minimum_rates:
  - :min_age: 0
    :max_age: 18
    :rate: 4.81
  - :min_age: 18
    :max_age: 21
    :rate: 6.83
  - :min_age: 21
    :max_age: 23
    :rate: 9.18
  - :min_age: 23
    :max_age: 1000
    :rate: 9.50
  :apprentice_rate: 4.81
  :accommodation_rate: 8.70
