---
- start_date: 2013-04-06
  end_date: 2014-04-05
  personal_allowance: 9440
  higher_allowance_1: 10500
  higher_allowance_2: 10660
  income_limit_for_personal_allowances: 26100.0

- start_date: 2014-04-06
  end_date: 2015-04-05
  personal_allowance: 10000
  higher_allowance_1: 10500
  higher_allowance_2: 10660
  income_limit_for_personal_allowances: 27000.0

- start_date: 2015-04-06
  end_date: 2016-04-05
  personal_allowance: 10600
  higher_allowance_1: 10600
  higher_allowance_2: 10660
  income_limit_for_personal_allowances: 27700.0

- start_date: 2016-04-06
  end_date: 2017-04-05
  personal_allowance: 11000
  higher_allowance_1: 11000
  higher_allowance_2: 11000
  income_limit_for_personal_allowances: 27700.0

- start_date: 2017-04-06
  end_date: 2018-04-05
  personal_allowance: 11000
  higher_allowance_1: 11000
  higher_allowance_2: 11000
  income_limit_for_personal_allowances: 28000.0

- start_date: 2018-04-06
  end_date: 2019-04-05
  personal_allowance: 11850
  higher_allowance_1: 11850
  higher_allowance_2: 11850
  income_limit_for_personal_allowances: 28900.0

- start_date: 2019-04-06
  end_date: 2020-04-05
  personal_allowance: 12500
  higher_allowance_1: 12500
  higher_allowance_2: 12500
  income_limit_for_personal_allowances: 29600.0

- start_date: 2020-04-06
  end_date: 2021-04-05
  personal_allowance: 12500
  higher_allowance_1: 12500
  higher_allowance_2: 12500
  income_limit_for_personal_allowances: 30200.0

- start_date: 2021-04-06
  end_date: 2022-04-05
  personal_allowance: 12500
  higher_allowance_1: 12500
  higher_allowance_2: 12500
  income_limit_for_personal_allowances: 30400.0

- start_date: 2022-04-06
  end_date: 2023-04-05
  personal_allowance: 12500
  higher_allowance_1: 12500
  higher_allowance_2: 12500
  income_limit_for_personal_allowances: 31400.0
