# This Smart Answer can use rates from the start of year (this year - 4),
# so to keep it tidy please delete anything earlier than that, but make
# sure you keep (in practise) the 6 most recent entries, or whatever covers
# the required period.
---
- start_date: 2017-04-06
  end_date: 2018-04-05
  max: "14,670"
  rate: 489
- start_date: 2018-04-06
  end_date: 2019-04-05
  max: "15,240"
  rate: 508
- start_date: 2019-04-06
  end_date: 2020-04-05
  max: "15,750"
  rate: 525
- start_date: 2020-04-06
  end_date: 2021-04-05
  max: "16,140"
  rate: 538
- start_date: 2021-04-06
  end_date: 2022-04-05
  max: "16,320"
  rate: 544
- start_date: 2022-04-06
  end_date: 2023-04-05
  max: "17,130"
  rate: 571
