# Only the current date is used, so this file should only have
# at most 2 items (current and future when uprating is coming),
# and usually 1. The last item in the file should have an end
# date of 2999-01-01
---
- start_date: 2022-04-11
  end_date: 2999-01-01
  weekly_rate: 141.85
  lower_weekly_rate: 85.00
